### ISSUE TITLE
`pip` doesn't like submodules

### ISSUE THREAD

**Issue by kg583** [TI-Toolkit/tivars_lib_py#15]
The `pip` command included in the README doesn't play nice with the `tokens` submodule; trying to fix this isn't helped by the submodule targeting a very old commit (see #8). Once everything gets ushered along upstream, I'll rework the `setuptools` integration, and also probably push to PyPI for good measure.

Until then, clone this repo directly with Git to be sure you download everything.

**Comment by tkbstudios** [comment]
Would it work if we clone the git submodules too into a directory and instead install the local tivars_lib_py project?

**Comment by tkbstudios** [comment]
Update:
`git clone --recursive https://github.com/TI-Toolkit/tivars_lib_py`
`pip3 install .\tivars_lib_py\`

Still the same issue even if you installed it with the submodules.

**Comment by rpitasky** [comment]
It's obviously nonstandard and undesirable but for a temporary solution look at what I did here:
https://github.com/TI-Toolkit/token_translation_extractor/tree/b4ef0d32801e3c8de1f6398401641a80ef0573e7
https://github.com/TI-Toolkit/token_translation_extractor/blob/b4ef0d32801e3c8de1f6398401641a80ef0573e7/extractor.py#L2-L3

**Comment by kg583** [comment]
Everything's on PyPI now: https://pypi.org/project/tivars/0.7.3/
